In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
print(type(my_list))

<class 'list'>


In [3]:
arr=np.array(my_list)
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(f"{l} is of type {type(l)}")

# to convert this 2d array to a matrix  we will use numpy
matrix =np.array(l)
print(f"{matrix} is of shape {matrix.shape}") # 3x3 matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] is of type <class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] is of shape (3, 3)


## Create an array using Numpy

    numpy.arange([start, ]stop, [step, ]dtype=None)

In [21]:
print(np.arange(0,11)) 
print(np.arange(10,-1,-1)) 
arr = np.arange(0, 1, 0.1, dtype=float)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## For an array of all zeros
    
    numpy.zeros(shape, dtype=float, order='C')


In [ ]:
# array of zeros
print(np.zeros(5,dtype=int)) # dedault dtype is Float
arr = np.zeros((3, 4),dtype=int) #(rows,columns)
print(arr)

# For all ones
    numpy.ones(shape, dtype=float, order='C')

In [24]:
print(np.ones(5,dtype=int))

[1 1 1 1 1]



### Ques1) create an 3x3 matix with all elements as 12 and after that subract 5 from each element

In [30]:
mat=np.ones((3,3),dtype=int)*12
print(f"{mat} is of dimension {mat.shape}")

mat=mat-5
print(mat)

[[12 12 12]
 [12 12 12]
 [12 12 12]] is of dimension (3, 3)
[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Linearly spaced array
    numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    
    num: The number of samples to generate. Default is 50.
    endpoint: If True (default), stop is the last value in the range. If False, it is not included.
    retstep: If True, return the step size between values along with the array. Default is False
  
  ### Note: Both start and end is included in the linearly spaced array


In [37]:
num=np.linspace(0,10,num=8) # both start and end are included 
print(num)
print(f"Length of num = {len(num)}") #8 since we requested for 8 equi-distant numbers

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
Length of num = 8


## Create an Identity Matrix
    which has only 1s in diagonal and rest of the element is zero
    numpy.eye(N, M=None, k=0, dtype=float, order='C')
    
    N: Number of rows in the output matrix.
    M: Number of columns in the output matrix. If None, it defaults to N (i.e., the matrix will be square).
    k: Diagonal in question. Default is 0, which refers to the main diagonal. Positive values refer to diagonals 
       above the main diagonal, and negative values refer to diagonals below.


In [39]:
print(np.eye(3,4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


## Create random numbers
The `numpy.random` module in NumPy provides functions for generating random numbers and performing random operations. This module is useful for tasks such as simulations, testing algorithms, and creating random datasets.

### **Key Functions in `numpy.random`**

Here are some commonly used functions from `numpy.random`:

1. **`numpy.random.rand`**

   Generates random numbers from a uniform distribution over [0, 1).

   ```python
   arr = np.random.rand(3, 2)
   print(arr)
   ```

   **Output**:
   ```
   [[0.96396653 0.73174974]
    [0.51684794 0.24066518]
    [0.27697977 0.06095282]]
   ```

2. **`numpy.random.randn`**

   Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

   ```python
   arr = np.random.randn(2, 3)
   print(arr)
   ```

   **Output**:
   ```
   [[ 1.20105982 -0.43100507  0.38559543]
    [-0.26714863 -0.33052843 -0.04681264]]
   ```

3. **`numpy.random.randint`**

   Generates random integers from a specified range.

   ```python
   arr = np.random.randint(1, 10, size=(2, 3))
   print(arr)
   ```

   **Output**:
   ```
   [[3 4 9]
    [1 5 7]]
   ```

4. **`numpy.random.choice`**

   Generates a random sample from a given array.

   ```python
   arr = np.random.choice([10, 20, 30, 40], size=5)
   print(arr)
   ```

   **Output**:
   ```
   [30 10 20 30 40]
   ```

5. **`numpy.random.seed`**

   Sets the seed for the random number generator to ensure reproducibility.

   ```python
   np.random.seed(0)
   arr = np.random.rand(2, 2)
   print(arr)
   ```

   **Output**:
   ```
   [[0.5488135  0.71518937]
    [0.60276338 0.54488318]]
   ```

6. **`numpy.random.permutation`**

   Randomly permutes a sequence or returns a permuted range.

   ```python
   arr = np.random.permutation([1, 2, 3, 4, 5])
   print(arr)
   ```

   **Output**:
   ```
   [3 1 5 4 2]
   ```

7. **`numpy.random.shuffle`**

   Shuffles the array in place.

   ```python
   import numpy as np

   arr = np.array([1, 2, 3, 4, 5])
   np.random.shuffle(arr)
   print(arr)
   ```

   **Output**:
   ```
   [2 4 1 5 3]
   ```
8. **`numpy.random.normal`**
    The numpy.random.normal function generates random numbers from a normal (Gaussian) distribution. This is useful for simulating data with a specific mean and standard deviation.
    ```python
    arr = np.random.normal(loc=0, scale=1, size=(3, 4))
    print(arr)
    
    loc: Mean of the distribution. Default is 0.0.
    scale: Standard deviation of the distribution. Default is 1.0.

    ```
     **Output**:
   ```
   [[ 1.13180988 -0.63446097  1.45985531 -0.45274872]
     [-0.67548934  1.28997832 -1.22416163 -0.30653762]
     [ 1.06822232  0.13236941  0.86727861 -0.04750807]]

   ```

## Reshape array
    numpy.reshape(a, newshape, order='C')


In [48]:
arr=np.arange(25)
print(arr)

rearrange=arr.reshape(5,5) #ensure the new shape should be able to accomodate exactlt the same number of element
print(rearrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Max and Min value

In [47]:
arr=np.random.randint(1,25,10)
print(arr)
print(f"max element is {arr.max()} at location {arr.argmax()}")
print(f"min element is {arr.min()} at location {arr.argmin()}")

[ 5 11 13 19 19  6  7 24 11  8]
max element is 24 at location 7
min element is 5 at location 0
