In [2]:
import numpy as np

In [4]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr+100 # add 100 to each number

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [6]:
arr/10 # divide each number by 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
arr**2 # square of each number

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
(arr+2)/10

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2])

In [9]:
arr+2*arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [10]:
100/arr #numpy dont produce an error with dividing by 0

C:\Users\himan\anaconda3\envs\data\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([         inf, 100.        ,  50.        ,  33.33333333,
        25.        ,  20.        ,  16.66666667,  14.28571429,
        12.5       ,  11.11111111,  10.        ])

In [13]:
arr/arr

C:\Users\himan\anaconda3\envs\data\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Array Aggregation Operations

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.sum(arr)  #sun of array

55

In [16]:
np.mean(arr)# Mean of array elements

5.0

In [17]:
np.max(arr) # Max value in the array

10

In [18]:
np.min(arr) # Min value in the array

0

In [23]:
np.sin(np.pi/2) # takes input in radian

1.0

In [37]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr_2d[0].sum() # sum of row=0

6

In [38]:
arr_2d[:,0].sum() #sum of column=0

12

In [43]:
arr_2d.sum() # sum of whole matrix

45

In [44]:
arr_2d.sum(axis=0) # sum of each columns

array([12, 15, 18])

In [45]:
arr_2d.sum(axis=1) # sum of each row

array([ 6, 15, 24])