# Practice Numpy
    There are ton of ways to do that so if you have any other way of doing that you can go ahead and continue that and if   not then i found this website very helpful 
```bash
https://www.machinelearningplus.com/python/101-numpy-exercises-python/
```

Note: Each cell will be the answer to the question from the above mentioned link

In [2]:
# Ques 1. Import numpy as np and see the version


import numpy as np
np.__version__

'1.21.5'

In [4]:
#Ques 2. How to create a 1D array 0 to 9?


arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Ques 3. Create a 3×3 numpy array of all True’s


# The numpy.full() function creates a new array of a specified shape 
# and fills it with a specified value.
# numpy.full(shape, fill_value, dtype=None, order='C')

print(np.full((3,3),True,dtype=bool) ) # method 1
other = np.repeat(True,9).reshape(3,-1) # method 2
print(other)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# Ques 4.  Extract all odd numbers from arr


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [11]:
# Ques 5. Replace all odd numbers in arr with -1

arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# The numpy.where() function
    Is used to return elements chosen from two arrays based on a condition. It can also be used to obtain indices of elements satisfying a condition. It is a powerful function for conditional operations and data manipulatio
    
    syntax:
    numpy.where(condition, x=True, y=False)
          when the condition is "True" x will be taken 
          when "False" value from y will be taken

In [13]:
# Ques 6. Replace all odd numbers in arr with -1 without changing arr


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(arr%2!=0, -1,arr))
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Ques 7. Convert a 1D array to a 2D array with 2 rows

arr=np.arange(10)
print(arr)
arr=arr.reshape(2,-1) # using -1 will automatically decide the number of columns
arr

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
# Ques 8.Stack arrays a and b vertically


a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=0) # axis=0 (row)

# Method 2:
np.vstack([a, b]) # vertical stack

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# Ques 9. Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a,b],axis=1)

# Method 2:
np.hstack([a,b]) # horizontal stack

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
# Ques 10. Create the following pattern without hardcoding. 
           #Use only numpy functions and the below input array a.
           # array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
        
        
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
np.repeat(a,3) # Repeats each element in a 3 times.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [35]:
np.tile(a,3) # Repeats the entire array a 3 times.

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
np.repeat(a,3)+np.tile(a,3) # this will add 2 arrays instead of concatenating 

array([2, 3, 4, 3, 4, 5, 4, 5, 6])

In [39]:
np.concatenate([np.repeat(a,3),np.tile(a,3)]) # correct

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
#Ques 11. Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

temp=np.intersect1d(a,b)
temp

array([2, 4])

In [46]:
# Ques 12. From array "a" remove all items present in array b


a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

union=np.intersect1d(a,b)
mask=~np.isin(a,b) #create a boolean mask where elements of 'a' are not in 'b'
a[mask]

#note: Both numpy and pandas has this isin function but they differ in syntax
# In Numpy synatx = numpy.isin(a,b)  [Elements common in a,b]
# In Pandas syntax = a.isin(b)

array([1, 2, 3, 4])

In [47]:
# Ques 13.Get the positions where elements of a and b match


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [51]:
# Ques 14.  Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
print(a[index])

# Method 2
a[(a>=5) & (a<=10)]

[ 6  9 10]


array([ 6,  9, 10])

## numpy.vectorize()
    Is a NumPy function that allows you to apply a Python function element-wise to arrays. It            transforms a regular Python function, which normally operates on scalars, into a vectorized    function that can operate on NumPy arrays.
    
    Syntax:
        np.vectorize(pyfunc, otypes=None, signature=None)


In [55]:
# Ques 15. Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[int])
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])